name: Auto Add Issues to Project

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/find-issues@v1
        with:
          project-url: https://github.com/orgs/Rivnam-Manvir/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
