name: Auto Add Issues to Project

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: srggrs/assign-one-project-github-action@1.2.1
        if: github.event.action == 'opened'
        with:
          project-url: https://github.com/orgs/Rivnam-Manvir/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
